services:
  shared-valkey:
    container_name: shared_valkey
    image: valkey/valkey:9-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
    networks:
      - valkey-net
    volumes:
      - ${VALKEY_DATA_LOCATION}:/data

networks:
  valkey-net:
    name: valkey-net
    driver: bridge
